# If not running interactively, don't do anything (leave this at the top of this file)
[[ $- != *i* ]] && return

# All the default Omarchy aliases and functions
# (don't mess with these directly, just overwrite them here!)
source ~/.local/share/omarchy/default/bash/rc

# Add your own exports, aliases, and functions here.
#
# Make an alias for invoking commands you use constantly
# alias p='python'
yt() {
  yt-dlp -f "bv*[ext=mp4]+ba[ext=m4a]/b[ext=mp4]" \
         --merge-output-format mp4 \
         -P "$HOME/Downloads" \
         "$@"
}
alias ytmp3='yt-dlp -x --audio-format mp3 --audio-quality 0 --embed-metadata --embed-thumbnail'
alias sleepnow="systemctl suspend"
